name: Build, Publish Docker Image, and Release Package

on:
  push:
    tags:
      - 'v*'  # This triggers on tag pushes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          kdrmdsrvr/gluetun-transmission-port-updater:latest
          kdrmdsrvr/gluetun-transmission-port-updater:${{ github.ref_name }}

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: 'Release created via GitHub Actions'
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Package code
      run: |
        mkdir -p release_package
        cp -r portupdate.sh Dockerfile release_package/
        tar -czvf release_package.tar.gz -C release_package .

    - name: Upload package to GitHub release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release_package.tar.gz
        asset_name: release_package.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
