name: Build and Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          kdrmdsrvr/gluetun-transmission-port-updater:latest
          kdrmdsrvr/gluetun-transmission-port-updater:${{ github.ref_name }}

    - name: Package code
      run: |
        mkdir -p release_package
        cp -r *.py Dockerfile release_package/
        tar -czvf release_package.tar.gz -C release_package .

    - name: Upload package to GitHub release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./release_package.tar.gz
        asset_name: release_package.tar.gz
        asset_content_type: application/gzip
